name : workflow1
on : workflow_dispatch
jobs:
  first job:
    runs-on: ubuntu-latest
    steps:
      -name: greeting
       run: echo "helloo"
      -name: wish
       run: echo "name"
      
    

